/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AppShareRouteImport } from './routes/app/share'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppMetricsRouteImport } from './routes/app/metrics'
import { Route as AppCorrelationsRouteImport } from './routes/app/correlations'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppPatientsIndexRouteImport } from './routes/app/patients/index'
import { Route as AppPatientsPatientIdRouteImport } from './routes/app/patients/$patientId'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppShareRoute = AppShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrelationsRoute = AppCorrelationsRouteImport.update({
  id: '/correlations',
  path: '/correlations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => AppPatientsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/correlations': typeof AppCorrelationsRoute
  '/app/metrics': typeof AppMetricsRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/share': typeof AppShareRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/correlations': typeof AppCorrelationsRoute
  '/app/metrics': typeof AppMetricsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/share': typeof AppShareRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients': typeof AppPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/correlations': typeof AppCorrelationsRoute
  '/app/metrics': typeof AppMetricsRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/share': typeof AppShareRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/correlations'
    | '/app/metrics'
    | '/app/patients'
    | '/app/profile'
    | '/app/share'
    | '/app/upload'
    | '/invite/$code'
    | '/app/'
    | '/app/admin/users'
    | '/app/patients/$patientId'
    | '/app/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/correlations'
    | '/app/metrics'
    | '/app/profile'
    | '/app/share'
    | '/app/upload'
    | '/invite/$code'
    | '/app'
    | '/app/admin/users'
    | '/app/patients/$patientId'
    | '/app/patients'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/admin'
    | '/app/correlations'
    | '/app/metrics'
    | '/app/patients'
    | '/app/profile'
    | '/app/share'
    | '/app/upload'
    | '/invite/$code'
    | '/app/'
    | '/app/admin/users'
    | '/app/patients/$patientId'
    | '/app/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/share': {
      id: '/app/share'
      path: '/share'
      fullPath: '/app/share'
      preLoaderRoute: typeof AppShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metrics': {
      id: '/app/metrics'
      path: '/metrics'
      fullPath: '/app/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/correlations': {
      id: '/app/correlations'
      path: '/correlations'
      fullPath: '/app/correlations'
      preLoaderRoute: typeof AppCorrelationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/': {
      id: '/app/patients/'
      path: '/'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/app/patients/$patientId': {
      id: '/app/patients/$patientId'
      path: '/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppPatientsRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPatientsRouteChildren {
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCorrelationsRoute: typeof AppCorrelationsRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppShareRoute: typeof AppShareRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCorrelationsRoute: AppCorrelationsRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppShareRoute: AppShareRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
