export type LabAnalyteCatalogEntry = {
  name: string;
  category: string;
  aliases: string[];
  isActive: boolean;
};

export const DEFAULT_LAB_ANALYTES = [
  {
    name: "Glucosa",
    category: "METABOLISMO",
    aliases: ["glucosa"],
    isActive: true,
  },
  {
    name: "Hemoglobina glucosilada (HbA1c)",
    category: "METABOLISMO",
    aliases: ["hemoglobina glucosilada", "hba1c", "hemoglobina glucosilada hba1c"],
    isActive: true,
  },
  {
    name: "Insulina",
    category: "METABOLISMO",
    aliases: ["insulina"],
    isActive: true,
  },
  {
    name: "Ácido úrico",
    category: "METABOLISMO",
    aliases: ["acido urico", "ácido úrico"],
    isActive: true,
  },
  {
    name: "Colesterol total",
    category: "LÍPIDOS",
    aliases: ["colesterol total", "cholesterol total", "colesterol"],
    isActive: true,
  },
  {
    name: "Colesterol HDL",
    category: "LÍPIDOS",
    aliases: ["colesterol hdl", "hdl"],
    isActive: true,
  },
  {
    name: "Colesterol LDL",
    category: "LÍPIDOS",
    aliases: ["colesterol ldl", "ldl"],
    isActive: true,
  },
  {
    name: "Triglicéridos",
    category: "LÍPIDOS",
    aliases: ["trigliceridos", "triglicéridos"],
    isActive: true,
  },
  {
    name: "Colesterol VLDL",
    category: "LÍPIDOS",
    aliases: ["colesterol vldl", "vldl"],
    isActive: true,
  },
  {
    name: "Índice aterogénico",
    category: "LÍPIDOS",
    aliases: ["indice aterogenico", "índice aterogénico", "indice aterogénico"],
    isActive: true,
  },
  {
    name: "Hemoglobina",
    category: "HEMATOLOGÍA",
    aliases: ["hemoglobina"],
    isActive: true,
  },
  {
    name: "Hematocrito",
    category: "HEMATOLOGÍA",
    aliases: ["hematocrito"],
    isActive: true,
  },
  {
    name: "Eritrocitos",
    category: "HEMATOLOGÍA",
    aliases: ["eritrocitos", "globulos rojos", "glóbulos rojos"],
    isActive: true,
  },
  {
    name: "Leucocitos",
    category: "HEMATOLOGÍA",
    aliases: ["leucocitos"],
    isActive: true,
  },
  {
    name: "Plaquetas",
    category: "HEMATOLOGÍA",
    aliases: ["plaquetas"],
    isActive: true,
  },
  {
    name: "VCM",
    category: "HEMATOLOGÍA",
    aliases: ["vcm", "volumen corpuscular medio"],
    isActive: true,
  },
  {
    name: "HCM",
    category: "HEMATOLOGÍA",
    aliases: ["hcm", "hemoglobina corpuscular media"],
    isActive: true,
  },
  {
    name: "CMHC",
    category: "HEMATOLOGÍA",
    aliases: ["cmhc", "concentracion media de hemoglobina corpuscular"],
    isActive: true,
  },
  {
    name: "Neutrófilos",
    category: "HEMATOLOGÍA",
    aliases: ["neutrofilos", "neutrófilos"],
    isActive: true,
  },
  {
    name: "Linfocitos",
    category: "HEMATOLOGÍA",
    aliases: ["linfocitos"],
    isActive: true,
  },
  {
    name: "Monocitos",
    category: "HEMATOLOGÍA",
    aliases: ["monocitos"],
    isActive: true,
  },
  {
    name: "Eosinófilos",
    category: "HEMATOLOGÍA",
    aliases: ["eosinofilos", "eosinófilos"],
    isActive: true,
  },
  {
    name: "Basófilos",
    category: "HEMATOLOGÍA",
    aliases: ["basofilos", "basófilos"],
    isActive: true,
  },
  {
    name: "Creatinina",
    category: "RENAL",
    aliases: ["creatinina"],
    isActive: true,
  },
  {
    name: "Nitrógeno ureico (BUN)",
    category: "RENAL",
    aliases: [
      "nitrogeno ureico",
      "nitrógeno ureico",
      "bun",
      "nitrogeno de urea en sangre (bun)",
      "nitrógeno de urea en sangre (bun)",
    ],
    isActive: true,
  },
  {
    name: "Urea",
    category: "RENAL",
    aliases: ["urea"],
    isActive: true,
  },
  {
    name: "Tasa de filtración glomerular (TFG)",
    category: "RENAL",
    aliases: ["tasa de filtracion glomerular", "tfg", "filtracion glomerular"],
    isActive: true,
  },
  {
    name: "Bilirrubina total",
    category: "HEPÁTICO",
    aliases: ["bilirrubina total"],
    isActive: true,
  },
  {
    name: "Bilirrubina directa",
    category: "HEPÁTICO",
    aliases: ["bilirrubina directa"],
    isActive: true,
  },
  {
    name: "Bilirrubina indirecta",
    category: "HEPÁTICO",
    aliases: ["bilirrubina indirecta"],
    isActive: true,
  },
  {
    name: "AST (TGO)",
    category: "HEPÁTICO",
    aliases: ["ast", "tgo", "ast tgo"],
    isActive: true,
  },
  {
    name: "ALT (TGP)",
    category: "HEPÁTICO",
    aliases: ["alt", "tgp", "alt tgp"],
    isActive: true,
  },
  {
    name: "Fosfatasa alcalina",
    category: "HEPÁTICO",
    aliases: ["fosfatasa alcalina"],
    isActive: true,
  },
  {
    name: "GGT",
    category: "HEPÁTICO",
    aliases: ["ggt", "gamma glutamil transferasa"],
    isActive: true,
  },
  {
    name: "Proteínas totales",
    category: "HEPÁTICO",
    aliases: ["proteinas totales", "proteínas totales"],
    isActive: true,
  },
  {
    name: "Albúmina",
    category: "HEPÁTICO",
    aliases: ["albumina", "albúmina"],
    isActive: true,
  },
  {
    name: "Globulinas",
    category: "HEPÁTICO",
    aliases: ["globulinas"],
    isActive: true,
  },
  {
    name: "Sodio",
    category: "ELECTROLITOS",
    aliases: ["sodio"],
    isActive: true,
  },
  {
    name: "Potasio",
    category: "ELECTROLITOS",
    aliases: ["potasio"],
    isActive: true,
  },
  {
    name: "Cloro",
    category: "ELECTROLITOS",
    aliases: ["cloro"],
    isActive: true,
  },
  {
    name: "Calcio",
    category: "ELECTROLITOS",
    aliases: ["calcio"],
    isActive: true,
  },
  {
    name: "Fósforo",
    category: "ELECTROLITOS",
    aliases: ["fosforo", "fósforo"],
    isActive: true,
  },
  {
    name: "Magnesio",
    category: "ELECTROLITOS",
    aliases: ["magnesio"],
    isActive: true,
  },
  {
    name: "TSH",
    category: "TIROIDES",
    aliases: ["tsh"],
    isActive: true,
  },
  {
    name: "T3 libre",
    category: "TIROIDES",
    aliases: ["t3 libre", "triiodotironina libre"],
    isActive: true,
  },
  {
    name: "T4 libre",
    category: "TIROIDES",
    aliases: ["t4 libre", "tiroxina libre"],
    isActive: true,
  },
  {
    name: "Vitamina D (25-OH)",
    category: "VITAMINAS",
    aliases: ["vitamina d", "vitamina d 25 oh", "25 oh vitamina d", "25-oh vitamina d"],
    isActive: true,
  },
  {
    name: "Vitamina B12",
    category: "VITAMINAS",
    aliases: ["vitamina b12", "b12"],
    isActive: true,
  },
  {
    name: "Ácido fólico",
    category: "VITAMINAS",
    aliases: ["acido folico", "ácido fólico", "folato"],
    isActive: true,
  },
  {
    name: "Proteína C reactiva (PCR)",
    category: "INFLAMACIÓN",
    aliases: ["proteina c reactiva", "pcr", "proteina c reactiva pcr"],
    isActive: true,
  },
  {
    name: "Velocidad de sedimentación (VSG)",
    category: "INFLAMACIÓN",
    aliases: ["velocidad de sedimentacion", "vsg", "velocidad de sedimentacion globular"],
    isActive: true,
  },
  {
    name: "Ferritina",
    category: "MARCADORES",
    aliases: ["ferritina"],
    isActive: true,
  },
  {
    name: "Hierro sérico",
    category: "MARCADORES",
    aliases: ["hierro serico", "hierro sérico"],
    isActive: true,
  },
  {
    name: "Transferrina",
    category: "MARCADORES",
    aliases: ["transferrina"],
    isActive: true,
  },
] satisfies readonly LabAnalyteCatalogEntry[];
